### ISSUE TITLE
Hoàn thiện ứng dụng và Demo

### ISSUE THREAD

**Issue by nnnonly** [parkouryb/SE04-Nhom30.1#13]

**Comment by nnnonly** [comment]
không biết chiều các bạn có rảnh không demo sớm, có gì sai sót còn kịp fix nè @parkouryb @vipno12tiger

**Comment by vipno12tiger** [comment]
tối nay tầm 20h mình họp nhóm để demo sản phẩm nhé. 
Phần Js tớ đang hoàn thiện nốt lấy sự kiện và môn học.
Còn phần demo là 1 ứng dụng android
Tớ mới học android nên mới code được 1 phần :(

**Comment by nnnonly** [comment]
Java android á hử?

**Comment by vipno12tiger** [comment]
đúng rồi cậu. Tớ đã hoàn thành được phần quan trọng nhất trong quản lý lớp học :> 
Đó là quản lý quỹ lớp :>>> hehe. 
Lát code xong java swing tớ sẽ làm nốt phần account :*)

**Comment by vipno12tiger** [comment]
@nnnonly Nhung ơi, tớ vừa connect DB với view xong.
Cậu pull code về rồi chỉnh sửa lại font chữ nhé.
Lúc đầu tớ mở bằng eclípe nên bị lỗi font :(((

**Comment by parkouryb** [comment]
Oke bạn yêu ahihi love you bùn vc mệt mỏi vc hihi yêu

**Comment by nnnonly** [comment]
ok thế là mình họp xong và hoàn thành gần đầy đủ các chức năng mong muốn ban đầu, vậy nên mình xin đóng issue này lại, hôm sau có phát triển thêm thì mình sẽ lại tiếp tục nhé. Cảm ơn các bạn đã đồng hành cùng mình trong suốt kì học này <3
