### ISSUE TITLE
How to add Lib

### ISSUE THREAD

**Issue by nnnonly** [parkouryb/SE04-Nhom30.1#6]

**Comment by vipno12tiger** [comment]
bạn thêm 2 thư viện ngoài vào để chạy được hibernate, nếu không là sẽ lỗi

**Comment by nnnonly** [comment]
Click chuột trái vào Libraries rồi chọn "Add Jar/Folder" nhá

**Comment by parkouryb** [comment]
Đây là dùng netbeans hả?

**Comment by nnnonly** [comment]
chuẩn á, với cả vì giao diện t làm ở netbeans, nên có những gói chỉ netbeans mới có, ví dụ mà dùng eclipse để chạy thì nó sẽ lỗi mấy gói đấy đấy

**Comment by nnnonly** [comment]
các bạn test xem có ok không, nếu ok thì reply để t close issue này nhé

**Comment by parkouryb** [comment]
mình oke rồi, Đăng thì sao?

**Comment by vipno12tiger** [comment]
tớ thêm được rồi

**Comment by nnnonly** [comment]
mình close lại issue này nhé
