### ISSUE TITLE
Lỗi thông báo không tìm thấy package mặc dù đã có?

### ISSUE THREAD

**Issue by vipno12tiger** [parkouryb/SE04-Nhom30.1#8]
![image](https://user-images.githubusercontent.com/58963650/103285816-b1092c80-4a11-11eb-8f93-93a697a2bda1.png)

**Comment by parkouryb** [comment]
mở database chưa, bật mysql chưa, tạo database tên là studentmanager chưa?

**Comment by parkouryb** [comment]
à định mệnh, không phải import thế, import Entity.* thôi

**Comment by parkouryb** [comment]
import Entity.*;
import Interactive.*;

**Comment by vipno12tiger** [comment]
=))) hết lỗi rồi nha mọi người. Tớ đóng issue này đây ._.
Cơ mà rõ ràng import như kia cũng đúng mà nhỉ 

> à định mệnh, không phải import thế, import Entity.* thôi
